### ISSUE TITLE
Problema npm run test1

### ISSUE THREAD

**Issue by SGL2324DAWZ** [SGL2324DAWZ/practica_dwec_gestor_presupuesto#1]
Disculpa Pedro no me di cuenta que era tu repo y no el mío. Ya estan los cambios subidos. @pedroprieto

**Comment by pedroprieto** [comment]
El fallo está aquí:
https://github.com/SGL2324DAWZ/practica_dwec_gestor_presupuesto/blob/ce4d8c8a299e1156fb069a427392164add6cbefa/js/gestionPresupuesto.js#L8

Un saludo!
