### ISSUE TITLE
Test 5

### ISSUE THREAD

**Issue by SGL2324DAWZ** [SGL2324DAWZ/practica_dwec_gestor_presupuesto#3]
Hola Pedro, 
tengo un problema con el test 5 y es que BorrarHandle no logro que pase el test, no se que he puesto, si me pudieras ayudar te lo agradecería.

Un saludo,
Selene.

@pedroprieto

**Comment by pedroprieto** [comment]
Buenas,

Tienes un fallo aquí:
https://github.com/SGL2324DAWZ/practica_dwec_gestor_presupuesto/blob/fd0a732ffc28ffe72c3a6dc6a7a6c663d62cc146/js/gestionPresupuestoWeb.js#L87-L90

Entiendo que deberías añadir esas propiedades a `objetoBorrar`, no a `botonBorrar`. Además, te falta añadir el manejador de evento del botón, cosa que sí que has hecho con el de editar:
https://github.com/SGL2324DAWZ/practica_dwec_gestor_presupuesto/blob/fd0a732ffc28ffe72c3a6dc6a7a6c663d62cc146/js/gestionPresupuestoWeb.js#L77

Un saludo!

**Comment by SGL2324DAWZ** [comment]
Aanda, por ir rapido, voy loca jaja, gracias Pedro!
